# -*- coding: UTF-8 -*-
class Estado:
	def estadoUf(self, uf):
		codigo = {  'RO': 11,
					'AC': 12,
					'AM': 13,
					'RR': 14,
					'PA': 15,
					'AP': 16,
					'TO': 17,
					'MA': 21,
					'PI': 22,
					'CE': 23,
					'RN': 24,
					'PB': 25,
					'PE': 26,
					'AL': 27,
					'SE': 28,
					'BA': 29,
					'MG': 31,
					'ES': 32,
					'RJ': 33,
					'SP': 35,
					'PR': 41,
					'SC': 42,
					'RS': 43,
					'MS': 50,
					'MT': 51,
					'GO': 52,
					'DF': 53}
		return codigo[uf]
	
	def estadoNome(self, uf):
		nome = {'AC': 'Acre',
				'AL': 'Alagoas',
				'AM': 'Amazonas',
				'AP': 'Amapá',
				'BA': 'Bahia',
				'CE': 'Ceará',
				'DF': 'Distrito Federal',
				'ES': 'Espírito Santo',
				'GO': 'Goiás',
				'MA': 'Maranhão',
				'MG': 'Minas Gerais',
				'MS': 'Mato Grosso do Sul',
				'MT': 'Mato Grosso',
				'PA': 'Pará',
				'PB': 'Paraíba',
				'PE': 'Pernambuco',
				'PI': 'Piauí',
				'PR': 'Paraná',
				'RJ': 'Rio de Janeiro',
				'RN': 'Rio Grande do Norte',
				'RO': 'Rondônia',
				'RR': 'Roraima',
				'RS': 'Rio Grande do Sul',
				'SC': 'Santa Catarina',
				'SE': 'Sergipe',
				'SP': 'São Paulo',
				'TO': 'Tocantins'}
		return nome[uf]
	
	def estados(self):
		estado={'AC': 'Acre',
				'AL': 'Alagoas',
				'AM': 'Amazonas',
				'AP': 'Amapá',
				'BA': 'Bahia',
				'CE': 'Ceará',
				'DF': 'Distrito Federal',
				'ES': 'Espírito Santo',
				'GO': 'Goiás',
				'MA': 'Maranhão',
				'MG': 'Minas Gerais',
				'MS': 'Mato Grosso do Sul',
				'MT': 'Mato Grosso',
				'PA': 'Pará',
				'PB': 'Paraíba',
				'PE': 'Pernambuco',
				'PI': 'Piauí',
				'PR': 'Paraná',
				'RJ': 'Rio de Janeiro',
				'RN': 'Rio Grande do Norte',
				'RO': 'Rondônia',
				'RR': 'Roraima',
				'RS': 'Rio Grande do Sul',
				'SC': 'Santa Catarina',
				'SE': 'Sergipe',
				'SP': 'São Paulo',
				'TO': 'Tocantins'}
		return estado  
